version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 148908330752.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "IMAGE TAG = $IMAGE_TAG"
      - docker build -t task-api .
      - docker tag task-api:latest 148908330752.dkr.ecr.eu-north-1.amazonaws.com/task-api:latest
      - docker tag task-api:latest 148908330752.dkr.ecr.eu-north-1.amazonaws.com/task-api:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image...
      - docker push 148908330752.dkr.ecr.eu-north-1.amazonaws.com/task-api:latest
      - docker push 148908330752.dkr.ecr.eu-north-1.amazonaws.com/task-api:$IMAGE_TAG

      - echo Prepare new task definition...
      - sed "s|IMAGE_TAG|$IMAGE_TAG|g" taskdef.json > taskdef_rendered.json

      - echo Register new task definition...
      - aws ecs register-task-definition --cli-input-json file://taskdef_rendered.json --region eu-north-1

      - echo Deploying to ECS...
      - aws ecs update-service --cluster task-cluster --service task-api-service-86o201j5 --task-definition task-api --region eu-north-1